name: Deploy the application
on: 
  workflow_dispatch:
    inputs:
      server:
        description: 'Deploy environement'
        required: true
        default: 'dev'

jobs:
  deploy-env:
    runs-on: ubuntu-latest
    steps:
     - name: Démarrage Workflow
       run: echo "Démarrage du Wokflow sur ${{github.ref}}"
     - name: Récupération code
       if: ${{github.ref == 'refs/heads/master'}}
       uses: actions/checkout@v4.1.1
     - name: Développement 
       if: github.event.inputs.server == 'dev'
       run: echo "Déploiement en Développement"
     - name: Qualification 
       if: github.event.inputs.server == 'qual'
       run: echo "Déploiement en Qualification"
     - name: Déploiement Production 
       if: github.event.inputs.server == 'prod'
       run: echo "Déploiement en Production"
      
