name: Deploy the application
on: 
  workflow_dispatch:
    inputs:
      server:
        description: 'Deploy environement'
        required: true
        default: 'dev'

jobs:
  deploy-env:
    runs-on: ubuntu-latest
    steps:
     - name: Démarrage Workflow
       run: echo "Démarrage du Wokflow sur ${{github.ref}}"
     - name: Changement branche
       run: echo "Changement de branche"
